import XCTest

@testable import LIOSKit

/// Fixtures generated by actually running `lios_protocol` (`protocol/src/lios_protocol`), not
/// reasoned about from reading it — see the fixture-generation script referenced in this repo's
/// `ios/README.md`. If `crypto.py`, `framing.py` or `pairing.py` ever changes shape, this is the
/// test that should fail, before a phone and a laptop ever try to talk to each other for real.
final class PythonInteropTests: XCTestCase {

    func testOpensABlobSealedByLiosProtocolCryptoAndFraming() throws {
        let key = try XCTUnwrap(Data(base64Encoded: "GUXZLNkRtkHhWiRQ8beTF7TUL6jbx5pgatC/KwLBBls="))
        let blob = try XCTUnwrap(
            Data(
                base64Encoded:
                    "4keFSpnE7yp6Pjaqkl2wgxm89Lik94DBtih0nT53LfjFS8N8PXHdzSu7n6TLVmDdWOO921Reht32kIX6ftEWcC58h5nvKU+fYygTI+QbAUoiQI/SPSY/yakvK8wV1t1O7HAvFbw0DYTzJIFAdnCEwM3S"
            ))
        let summary = ItemSummary(
            id: UUID(uuidString: "5b1b6f1a-9c1e-4b0a-9c1e-4b0a9c1e4b0a")!, senderDeviceId: UUID(),
            targetDeviceId: nil, sizeBytes: 114, createdAt: Date())

        let item = try LiosItem.open(summary: summary, sealedBlob: blob, groupKey: key, direction: .received)
        XCTAssertEqual(item.type, .file)
        XCTAssertEqual(item.filename, "notes.pdf")
        XCTAssertEqual(item.mimeType, "application/pdf")
        XCTAssertEqual(item.payload, Data("fake pdf bytes".utf8))
    }

    func testDecodesAQrUriProducedByLiosProtocolPairing() throws {
        let uri =
            "lios://pair/eyJyZWxheV91cmwiOiJodHRwczovL2xpb3MuZnJlZGVyaWtiZXJnLm5ldCIsInBhaXJpbmdfY29kZSI6IkFCQ0QyMzQ1IiwiZ3JvdXBfa2V5X2I2NCI6IkdVWFpMTmtSdGtIaFdpUlE4YmVURjdUVUw2amJ4NXBnYXRDL0t3TEJCbHM9In0="
        let payload = try Pairing.decodeQrUri(uri)
        XCTAssertEqual(payload.relayUrl, "https://lios.frederikberg.net")
        XCTAssertEqual(payload.pairingCode, "ABCD2345")
        XCTAssertEqual(try payload.groupKey(), Data(base64Encoded: "GUXZLNkRtkHhWiRQ8beTF7TUL6jbx5pgatC/KwLBBls="))
    }
}
