{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lios.fullname" . }}
  labels:
    {{- include "lios.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.existingSecretKeys.databaseUrl }}: {{ .Values.secret.databaseUrl | quote }}
  {{- if .Values.secret.apnsKeyId }}
  {{ .Values.existingSecretKeys.apnsKeyId }}: {{ .Values.secret.apnsKeyId | quote }}
  {{- end }}
  {{- if .Values.secret.apnsTeamId }}
  {{ .Values.existingSecretKeys.apnsTeamId }}: {{ .Values.secret.apnsTeamId | quote }}
  {{- end }}
  {{- if .Values.secret.apnsAuthKeyB64 }}
  {{ .Values.existingSecretKeys.apnsAuthKeyB64 }}: {{ .Values.secret.apnsAuthKeyB64 | quote }}
  {{- end }}
{{- end }}
