"""Pure URL and header construction against the relay's REST/WebSocket surface.

Kept free of any network call so the shape of every request is unit-testable without a
running relay. `lios_relay.api.*` (in the sibling `relay/` package) is the authority on the
routes themselves; this module only builds what a caller needs to hit them.
"""

from __future__ import annotations

import base64
from datetime import datetime
from urllib.parse import quote, urlencode

from lios_protocol.headers import (
    ITEM_ID_HEADER,
    SEALED_PREVIEW_HEADER,
    TARGET_DEVICE_ID_QUERY_PARAM,
)


def _base(relay_url: str) -> str:
    return relay_url.rstrip("/")


def items_url(relay_url: str, *, target_device_id: str | None = None) -> str:
    """`POST /api/items`, optionally narrowed to one recipient device via the query param
    `lios_protocol.headers.TARGET_DEVICE_ID_QUERY_PARAM` -- the item id and sealed preview ride
    as headers instead, see :func:`create_item_headers`."""
    url = f"{_base(relay_url)}/api/items"
    if target_device_id:
        url += "?" + urlencode({TARGET_DEVICE_ID_QUERY_PARAM: target_device_id})
    return url


def create_item_headers(
    *, device_token: str, item_id: str, content_length: int, sealed_preview: bytes | None = None
) -> dict[str, str]:
    """Headers for `POST /api/items`, per `lios_protocol.headers`.

    `item_id` is generated by the caller before sealing -- it is the sealed blob's own AEAD
    associated data, so it must exist before the item is ever sealed, let alone sent.
    """
    headers = auth_header(device_token)
    headers["Content-Type"] = "application/octet-stream"
    headers["Content-Length"] = str(content_length)
    headers[ITEM_ID_HEADER] = item_id
    if sealed_preview is not None:
        headers[SEALED_PREVIEW_HEADER] = base64.b64encode(sealed_preview).decode("ascii")
    return headers


def item_url(relay_url: str, item_id: str) -> str:
    """`GET`/`DELETE /api/items/{id}`."""
    return f"{_base(relay_url)}/api/items/{quote(item_id, safe='')}"


def items_since_url(relay_url: str, since: datetime) -> str:
    """`GET /api/items?since=...`, the catch-up list for a client that was offline."""
    return f"{_base(relay_url)}/api/items?" + urlencode({"since": since.isoformat()})


def stream_url(relay_url: str) -> str:
    """`GET /api/stream`, as the `ws://`/`wss://` URL a WebSocket client connects to.

    Raises:
        ValueError: `relay_url` is neither an `http://` nor an `https://` URL.
    """
    base = _base(relay_url)
    if base.startswith("https://"):
        return "wss://" + base[len("https://") :] + "/api/stream"
    if base.startswith("http://"):
        return "ws://" + base[len("http://") :] + "/api/stream"
    raise ValueError(f"relay_url must start with http:// or https://, got {relay_url!r}")


def bootstrap_url(relay_url: str) -> str:
    """`POST /api/devices/bootstrap` -- registering the very first device in an empty fleet."""
    return f"{_base(relay_url)}/api/devices/bootstrap"


def pairing_sessions_url(relay_url: str) -> str:
    """`POST /api/devices/pairing-sessions`."""
    return f"{_base(relay_url)}/api/devices/pairing-sessions"


def pair_url(relay_url: str) -> str:
    """`POST /api/devices/pair`."""
    return f"{_base(relay_url)}/api/devices/pair"


def push_token_url(relay_url: str, device_id: str) -> str:
    """`POST /api/devices/{id}/push-token`."""
    return f"{_base(relay_url)}/api/devices/{quote(device_id, safe='')}/push-token"


def auth_header(device_token: str) -> dict[str, str]:
    """The bearer-token `Authorization` header every endpoint but pairing itself requires."""
    return {"Authorization": f"Bearer {device_token}"}
