"""Building and opening one item's sealed envelope -- framing and encryption composed.

Metadata keys inside the frame (`lios_protocol.framing` deliberately knows nothing about what
its bytes mean -- see its own module docstring): `type` is `"text"`, `"image"` or `"file"`;
`filename` and `mime_type` are present for `image`/`file` items and absent for `text`. These
mirror LIOSKit's `FrameMetadataKey`/`ItemType` exactly, not a Linux-only convention -- the two
platforms must agree on the wire, not each invent their own shape.

The AEAD associated data is `f"{item_id}|{size_bytes}"`: the item's own clear, relay-visible
id and the sealed blob's own byte count, mirroring `LiosItem.seal`/`.open` in LIOSKit bit for
bit. `size_bytes` is computable before ever sealing -- AES-GCM's ciphertext is exactly as long
as its plaintext, so `size_bytes = NONCE_SIZE + len(frame) + TAG_SIZE` always -- which is what
lets a sender authenticate a size the relay has not confirmed yet. `item_id` is lowercased
before encoding: Python's `str(uuid.UUID(...))` is already lowercase, but Swift's `uuidString`
is uppercase, and the two platforms must agree on one case for the authenticated bytes to
match.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from lios_protocol import crypto, framing
from lios_protocol.frame import FILENAME_KEY, MIME_TYPE_KEY, TYPE_KEY

#: AES-GCM's tag length in bytes (128 bits) -- not exported by `lios_protocol.crypto`, which
#: only names the nonce size, since the tag length is AESGCM's own fixed constant rather than
#: a choice this project made. Mirrors the literal `16` in LIOSKit's `LiosItem.seal`.
_TAG_SIZE = 16

#: How much of a text item's content rides in the sealed preview -- a notification banner, not
#: a reading surface. Mirrors `PushPreview.previewCharacterLimit` in LIOSKit exactly.
PREVIEW_CHARACTER_LIMIT = 120


@dataclass(frozen=True)
class SealedItem:
    """Everything `relaylink.rest.create_item` needs: the blob to upload and its own size."""

    blob: bytes
    size_bytes: int


@dataclass(frozen=True)
class DecodedItem:
    """One item's metadata and payload, after opening its sealed envelope."""

    kind: str
    filename: str | None
    content_type: str | None
    payload: bytes


@dataclass(frozen=True)
class ItemPreview:
    """The small preview a sealed-preview blob carries -- see `build_sealed_preview`."""

    kind: str
    preview: str | None
    filename: str | None


def _item_associated_data(item_id: str, size_bytes: int) -> bytes:
    """The bytes both `build_sealed_item` and `open_sealed_item` authenticate but never
    encrypt -- the item's clear id and the sealed blob's own byte count."""
    return f"{item_id.lower()}|{size_bytes}".encode()


def _preview_associated_data(item_id: str) -> bytes:
    """A sealed preview's associated data is the item id alone, no size -- distinct from
    `_item_associated_data`, matching `PushPreview.seal`/`.open` in LIOSKit."""
    return item_id.lower().encode()


def build_sealed_item(
    *,
    group_key: bytes,
    kind: str,
    payload: bytes,
    item_id: str,
    filename: str | None = None,
    content_type: str | None = None,
) -> SealedItem:
    """Frame `payload` with its metadata, then seal it under the fleet's group key.

    `item_id` must be generated by the caller before calling this -- it is authenticated here
    and must be sent as `X-Item-Id` on `POST /api/items` unchanged.
    """
    metadata = {TYPE_KEY: kind}
    if filename is not None:
        metadata[FILENAME_KEY] = filename
    if content_type is not None:
        metadata[MIME_TYPE_KEY] = content_type
    frame = framing.pack(metadata, payload)
    size_bytes = crypto.NONCE_SIZE + len(frame) + _TAG_SIZE
    blob = crypto.seal(
        group_key, frame, associated_data=_item_associated_data(item_id, size_bytes)
    )
    return SealedItem(blob=blob, size_bytes=size_bytes)


def open_sealed_item(
    *, group_key: bytes, sealed_blob: bytes, item_id: str, size_bytes: int
) -> DecodedItem:
    """Reverse :func:`build_sealed_item`.

    `size_bytes` is the relay's own report of the blob's length (`ItemSummary.size_bytes`) --
    it must match what the sender authenticated. A mismatch raises `TamperError` even under
    the right key, which is the point: a truncated or substituted blob is caught here rather
    than producing a malformed frame.

    Raises:
        ValueError: the blob is malformed, or the frame's metadata does not parse.
        lios_protocol.crypto.TamperError: the blob failed authentication.
    """
    frame = crypto.open_sealed(
        group_key, sealed_blob, associated_data=_item_associated_data(item_id, size_bytes)
    )
    metadata, payload = framing.unpack(frame)
    return DecodedItem(
        kind=metadata.get(TYPE_KEY, "file"),
        filename=metadata.get(FILENAME_KEY),
        content_type=metadata.get(MIME_TYPE_KEY),
        payload=payload,
    )


def build_sealed_preview(
    *, group_key: bytes, item_id: str, kind: str, preview: str | None, filename: str | None
) -> bytes:
    """Seal a small preview alongside the full item, for `X-Sealed-Preview`.

    The relay is end-to-end encrypted and cannot compose a push banner itself; an iOS
    Notification Service Extension decrypts this instead, without fetching the item's own
    payload. `preview` is a short prefix of the text for a text item only -- never set for
    image or file, so a truncation bug cannot leak more than intended; `filename` is the
    reverse. Mirrors `PushPreview.seal` in LIOSKit exactly.
    """
    payload = json.dumps(
        {TYPE_KEY: kind, "preview": preview, FILENAME_KEY: filename}, separators=(",", ":")
    ).encode("utf-8")
    return crypto.seal(group_key, payload, associated_data=_preview_associated_data(item_id))


def open_sealed_preview(
    *, group_key: bytes, sealed_blob: bytes, item_id: str
) -> ItemPreview | None:
    """Reverse :func:`build_sealed_preview`.

    Returns `None` for an empty `sealed_blob` -- the sender (or an older relay) attached no
    preview at all, the expected degrade rather than a tamper attempt. Mirrors
    `PushPreview.open`'s same convention in LIOSKit.
    """
    if not sealed_blob:
        return None
    payload = crypto.open_sealed(
        group_key, sealed_blob, associated_data=_preview_associated_data(item_id)
    )
    data = json.loads(payload)
    return ItemPreview(
        kind=data.get(TYPE_KEY, "file"),
        preview=data.get("preview"),
        filename=data.get(FILENAME_KEY),
    )


def truncate_preview_text(text: str, *, limit: int = PREVIEW_CHARACTER_LIMIT) -> str:
    """Shorten `text` to `limit` characters for a sealed preview, with a trailing ellipsis."""
    return text if len(text) <= limit else text[: limit - 3] + "..."
