import Foundation

/// One item after its sealed blob has been opened and unframed — the shape every receive-side
/// screen (notification tap, history) works with, rather than each re-deriving it from the raw
/// frame.
public struct LiosItem: Sendable, Identifiable {
    public let id: UUID
    public let senderDeviceId: UUID
    public let type: ItemType
    public let filename: String?
    public let mimeType: String?
    public let payload: Data
    public let createdAt: Date
    public let direction: ItemDirection

    public init(
        id: UUID, senderDeviceId: UUID, type: ItemType, filename: String?, mimeType: String?,
        payload: Data, createdAt: Date, direction: ItemDirection
    ) {
        self.id = id
        self.senderDeviceId = senderDeviceId
        self.type = type
        self.filename = filename
        self.mimeType = mimeType
        self.payload = payload
        self.createdAt = createdAt
        self.direction = direction
    }

    /// The bytes both `open` and `seal` authenticate but never encrypt: the item's clear,
    /// relay-visible id and the sealed blob's own byte count. Kept as one function so sender and
    /// receiver cannot drift on what "associated data" means.
    ///
    /// `sizeBytes` is always `nonce (12) + frame.count + tag (16)` — computable by the sender
    /// before it ever talks to the relay, and exactly what the relay reports back afterwards,
    /// since it never inspects the blob and only ever measures the bytes it was handed. That
    /// is what lets the sender authenticate against a size the relay has not confirmed yet.
    ///
    /// 🚨 `uuidString` is uppercase; Python's `str(uuid.UUID(...))` is lowercase. Both this app
    /// and any Python sender/receiver must agree on one case for the bytes to match — lowercased
    /// here since that is Python's default and this is the side that has to adapt.
    private static func associatedData(id: UUID, sizeBytes: Int) -> Data {
        Data("\(id.uuidString.lowercased())|\(sizeBytes)".utf8)
    }

    /// Decrypt and unframe one item, given its clear summary (as reported by the relay) and its
    /// ciphertext blob fetched from `GET /api/items/{id}`. `direction` is never inferred from the
    /// summary — the same blob is opened for a notification tap (always `.received`) and for
    /// sent-history sync (always `.sent`), and only the caller knows which fetch this is.
    ///
    /// - Throws: `Sealing.TamperError` if the blob does not verify under `groupKey` and this
    ///   summary's associated data. `Framing.MalformedFrameError` if the plaintext frame is
    ///   malformed. A `DecodingError` if the metadata's `type` is missing or unrecognised.
    public static func open(
        summary: ItemSummary, sealedBlob: Data, groupKey: Data, direction: ItemDirection
    ) throws -> LiosItem {
        let aad = associatedData(id: summary.id, sizeBytes: summary.sizeBytes)
        let plaintext = try Sealing.open(key: groupKey, blob: sealedBlob, associatedData: aad)
        let (metadata, payload) = try Framing.unpack(frame: plaintext)
        guard let typeString = metadata[FrameMetadataKey.type], let type = ItemType(rawValue: typeString) else {
            throw DecodingError.dataCorrupted(
                DecodingError.Context(codingPath: [], debugDescription: "frame metadata missing a recognised 'type'"))
        }
        return LiosItem(
            id: summary.id, senderDeviceId: summary.senderDeviceId, type: type,
            filename: metadata[FrameMetadataKey.filename], mimeType: metadata[FrameMetadataKey.mimeType],
            payload: payload, createdAt: summary.createdAt, direction: direction)
    }

    /// Everything a sender needs to hand `RelayClient.createItem` — the sealed blob it uploads,
    /// and the size that blob will be, computed before sealing so the caller never has to derive
    /// it a second way.
    public struct Sealed: Sendable {
        public let id: UUID
        public let blob: Data
        public let sizeBytes: Int
    }

    /// Seal one item for sending: frames `metadata` and `payload`, then seals the frame under
    /// `groupKey` with `id`'s and the resulting blob's own size as associated data — the
    /// send-side counterpart of `open`. `id` is generated by the caller (a fresh `UUID()`), not
    /// the relay — the relay only ever stores and echoes back the id it is handed.
    public static func seal(
        id: UUID, type: ItemType, filename: String?, mimeType: String?, payload: Data, groupKey: Data
    ) throws -> Sealed {
        var metadata: [String: String] = [FrameMetadataKey.type: type.rawValue]
        if let filename { metadata[FrameMetadataKey.filename] = filename }
        if let mimeType { metadata[FrameMetadataKey.mimeType] = mimeType }
        let frame = Framing.pack(metadata: metadata, payload: payload)
        let sizeBytes = 12 + frame.count + 16
        let aad = associatedData(id: id, sizeBytes: sizeBytes)
        let blob = try Sealing.seal(key: groupKey, plaintext: frame, associatedData: aad)
        return Sealed(id: id, blob: blob, sizeBytes: sizeBytes)
    }
}
